 Feature scaling : standardization / Normalization

In [1]:
from sklearn.preprocessing import StandardScaler , MinMaxScaler

In [2]:
scaler = StandardScaler()

In [ ]:
x_scaled = scaler.fit_transform()

In [10]:
scaler = MinMaxScaler()

In [ ]:
x_scaled = scaler.fit_transform()

In [11]:
import pandas as pd
from sklearn.preprocessing import StandardScaler , MinMaxScaler
from sklearn.model_selection import train_test_split

In [14]:
data={
    'StudyHours' : [1, 2, 3, 4, 5],
    'TestScore' : [40, 50, 60, 70, 80]   
}
df = pd.DataFrame(data)

In [15]:
df

   StudyHours  TestScore
0           1         40
1           2         50
2           3         60
3           4         70
4           5         80

In [16]:
standard_scaler = StandardScaler()

In [18]:
standard_scaled = standard_scaler.fit_transform(df)

In [23]:
print("Standard Scaler Output:")
print(pd.DataFrame(standard_scaled, columns=['StudyHours','TestScore']))

Standard Scaler Output:
   StudyHours  TestScore
0   -1.414214  -1.414214
1   -0.707107  -0.707107
2    0.000000   0.000000
3    0.707107   0.707107
4    1.414214   1.414214

In [26]:
import pandas as pd
from sklearn.preprocessing import StandardScaler , MinMaxScaler
from sklearn.model_selection import train_test_split

In [27]:
data={
    'StudyHours' : [1, 2, 3, 4, 5],
    'TestScore' : [40, 50, 60, 70, 80]   
}
df = pd.DataFrame(data)

In [28]:
df

   StudyHours  TestScore
0           1         40
1           2         50
2           3         60
3           4         70
4           5         80

In [32]:
minmax_scaler = MinMaxScaler()

In [34]:
minmax_scaled = minmax_scaler.fit_transform(df)

In [35]:
print("Nor Scaler Output:")
print(pd.DataFrame(minmax_scaled, columns=['StudyHours','TestScore']))

Nor Scaler Output:
   StudyHours  TestScore
0        0.00       0.00
1        0.25       0.25
2        0.50       0.50
3        0.75       0.75
4        1.00       1.00

In [6]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_csv(r'C:\Users\123\Desktop\Cars.csv')

In [8]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [9]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Force               6
Land                6
Isuzu               5
Kia                 4
Ambassador          4
Daewoo              3
MG                  3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

In [10]:
df['brand'].nunique() # total categories

32

3. OneHotEncoding using SKlearn

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1], test_size= 0.2,random_state=42)

In [12]:
x_train

         brand  km_driven    fuel                 owner
6518      Tata       2560  Petrol           First Owner
6144     Honda      80000  Petrol          Second Owner
6381   Hyundai     150000  Diesel  Fourth & Above Owner
438     Maruti     120000  Diesel          Second Owner
5939    Maruti      25000  Petrol           First Owner
...        ...        ...     ...                   ...
5226  Mahindra     120000  Diesel           First Owner
5390    Maruti      80000  Diesel          Second Owner
860    Hyundai      35000  Petrol           First Owner
7603    Maruti      27000  Diesel           First Owner
7270    Maruti      70000  Petrol          Second Owner

[6502 rows x 4 columns]

In [13]:
from sklearn.preprocessing import OneHotEncoder

In [14]:
ohe = OneHotEncoder(drop='first',dtype=np.int32,sparse_output = False)

In [15]:
x_train_new = ohe.fit_transform(x_train[['fuel','owner']])

In [16]:
x_test_new = ohe.transform(x_test[['fuel','owner']])

In [17]:
x_train_new.shape

(6502, 7)

In [18]:
np.hstack((x_train[['brand','km_driven']].values,x_train_new))

array([['Tata', 2560, 0, ..., 0, 0, 0],
       ['Honda', 80000, 0, ..., 1, 0, 0],
       ['Hyundai', 150000, 1, ..., 0, 0, 0],
       ...,
       ['Hyundai', 35000, 0, ..., 0, 0, 0],
       ['Maruti', 27000, 1, ..., 0, 0, 0],
       ['Maruti', 70000, 0, ..., 1, 0, 0]], dtype=object)

4.OneHotEncoding with top Categories

In [19]:
counts = df['brand'].value_counts()

In [20]:
df['brand'].nunique()
threshold = 100

In [21]:
repl = counts[counts <= threshold].index

In [22]:
repl

Index(['Nissan', 'Jaguar', 'Volvo', 'Datsun', 'Mercedes-Benz', 'Fiat', 'Audi',
       'Lexus', 'Jeep', 'Mitsubishi', 'Force', 'Land', 'Isuzu', 'Kia',
       'Ambassador', 'Daewoo', 'MG', 'Ashok', 'Opel', 'Peugeot'],
      dtype='object', name='brand')

In [23]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon'))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False,False

Column Transformer:

In [43]:
import numpy as np 
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import StandardScaler , MinMaxScaler

In [40]:
df = pd.read_csv(r'C:\Users\123\Desktop\covid_toy.csv')

In [41]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [53]:
df=df.fillna(df['fever'].mean())

In [46]:
from sklearn.model_selection import train_test_split
x_train , x_test, y_train, y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

1.Aam Zindagi

In [61]:
#ordinalencoding --> cough
oe = OrdinalEncoder(categories=[['Mild','Strong']])
x_train_cough = oe.fit_transform(x_train[['cough']])

# also the test data
x_test_cough = oe.fit_transform(x_test[['cough']])

x_train_cough.shape

(80, 1)

In [74]:
# OneHotEncoder ---> gender,city
ohe = OneHotEncoder(drop='first',sparse_output=False)
x_train_gender_city = ohe.fit_transform(x_train[['gender','city']])

# also the test data
x_test_gender_city = ohe.fit_transform(x_test[['gender','city']])

x_train_gender_city.shape

(80, 4)

In [82]:
# Extracting Age
x_train_age = x_train.drop(columns=['gender','cough','city']).values

# also the test data
x_test_age = x_test.drop(columns=['gender','cough','city']).values

x_train_age.shape

(80, 2)

In [85]:
x_train_transformed = np.concatenate((x_train_age,x_train_gender_city,x_train_cough),axis=1)

# also the test data
x_test_transformed = np.concatenate((x_test_age,x_test_gender_city,x_test_cough),axis=1)

x_train_transformed.shape

(80, 7)

Mentos Zindagi

In [86]:
from sklearn.compose import ColumnTransformer

In [89]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf2',OneHotEncoder(drop='first',sparse_output=False),['gender','city'])   
],remainder='passthrough')

In [101]:
x_train_transformed = transformer.fit_transform(x_train).shape
print(x_train_transformed)

(80, 7)

In [103]:
x_test_transformed = transformer.transform(x_test)
print(x_test_transformed)

[[  0.   0.   0.   1.   0.  69. 103.]
 [  1.   1.   0.   1.   0.  70. 103.]
 [  1.   0.   0.   0.   0.  42.  nan]
 [  0.   1.   1.   0.   0.  19. 101.]
 [  1.   0.   0.   1.   0.  71.  98.]
 [  0.   0.   0.   0.   0.  12. 104.]
 [  0.   1.   0.   1.   0.   5. 102.]
 [  0.   0.   0.   0.   0.  16. 103.]
 [  0.   0.   0.   0.   1.  65.  98.]
 [  1.   1.   0.   0.   0.  14. 101.]
 [  0.   0.   1.   0.   0.  49. 101.]
 [  1.   1.   0.   0.   1.  23.  98.]
 [  1.   0.   0.   0.   1.  34.  nan]
 [  0.   0.   0.   1.   0.  31.  98.]
 [  0.   0.   0.   0.   0.  64.  98.]
 [  0.   0.   0.   0.   0.  22.  99.]
 [  1.   0.   0.   1.   0.  25.  99.]
 [  0.   0.   1.   0.   0.  49. 102.]
 [  0.   1.   0.   0.   0.  64. 102.]
 [  0.   1.   1.   0.   0.  42. 101.]]

pipeline